default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: poety_development

test:
  <<: *default
  database: poety_test
production:
  <<: *default
  database: poety_production
  username: poety
  password: <%= ENV['POETY_DATABASE_PASSWORD'] %>
